# Configuration for librarian-puppet. For example:
#
# forge "http://forge.puppetlabs.com"
#
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
#

forge "http://forge.puppetlabs.com"
mod 'puppetlabs/postgresql'
