Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"

    config.vm.define "db" do |db|
      db.vm.network "private_network", ip: "192.168.50.2"
      # :forwarded_port, guest: 5432, host: 5432, "private_network", ip: "192.168.50.4"
      db.vm.provision :shell, :path => "shell/main.sh"
      db.vm.provision :puppet
    end
end
